name: "Build Validation"
run-name: Build App

on:
  push:
    branches:
      - master
      - dev
      - dev-plus
    paths:
      - "**.cs"
      - "**.csproj"
env:
  WORKING_DIR: src
  DOTNET_VERSION: "6.0.x"

jobs:
  build:
    name: build validation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
    steps:
      - name: Checkout the code repository.
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: restore project deps
        working-directory: ${{ env.WORKING_DIR }}
        run: dotnet restore

      - name: build project.
        working-directory: ${{ env.WORKING_DIR }}
        run: dotnet build MinimalAPIS.csproj --no-restore -c Release