name: "main workflow"

on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./
    steps:
      - name: view dir
        run: ls
      # - name: restore packages
      #   run: dotnet restore

      # - name: build app
      #   run: dotnet build
      
      # - name: publish app
      #   run: mkdir output && dotnet publish -c Release --output=./output --no-self-contained
      
      # - name: show output directory content
      #   run: cd output && ls
