name: "main workflow"

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: view dir
        working-directory: ./src
        run: ls
      - name: restore packages
        working-directory: ./src
        run: dotnet restore ./MinimalAPIS.csproj
        
      # - name: build app
      #   working-directory: .
      #   run: dotnet build
      
      # - name: publish app
      #   run: mkdir output && dotnet publish -c Release --output=./output --no-self-contained
      
      # - name: show output directory content
      #   run: cd output && ls
