name: "main workflow"
# run-name: ${{ github.actor }} is testing out GitHub actions

on:
  push:
    branches:
      - "master"
      - "dev"
jobs:
  Explore-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code repository.
        uses: actions/checkout@v3
      - name: list files in src dirrecoty
        working-directory: src
        run: ls 
      - name: restore project deps
        working-directory: src
        run: dotnet restore
      - name: show refs
        working-directory: src
        run: dotnet list package
      - run: echo "This job is ${{ job.status }}"

      # - name: restore packages
      #   working-directory: src
      #   run: dotnet restore ./MinimalAPIS.csproj

      # - name: build app
      #   working-directory: .
      #   run: dotnet build

      # - name: publish app
      #   run: mkdir output && dotnet publish -c Release --output=./output --no-self-contained

      # - name: show output directory content
      #   run: cd output && ls
